apiVersion: apps/v1
kind: Deployment
metadata:
  name: iron-bank
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: iron-bank-server
        envFrom:
        - configMapRef:
            name: iron-bank-config
        - secretRef:
            name: iron-bank-secret
