apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: iron-bank-config
    behavior: merge
    envs:
      - config/application.properties

resources:
  - ../../base
patches:
- path: deployment-replica-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: iron-bank
- path: hpa-replica-patch.yaml
  target:
    group: autoscaling
    version: v2
    kind: HorizontalPodAutoscaler
    name: iron-bank