version: '3.7'
services:
  app-native:
    build:
      context: .
      dockerfile: native.dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/iron-bank?user=postgres&password=root
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: false
    ports:
      - "8090:8080"
  app-jvm:
    build:
      context: .
      dockerfile: jvm.dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/iron-bank?user=postgres&password=root
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: false
    ports:
      - "8095:8080"
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: iron-bank
      POSTGRES_PASSWORD: root
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg-data:
    name: pg-data-java