apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app.kubernetes.io/name: iron-bank
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: iron-bank
- includeSelectors: false
  includeTemplates: true
  pairs:
    app.kubernetes.io/version: _VERSION

configMapGenerator:
  - name: iron-bank-config
    envs:
      - config/application.properties
secretGenerator:
  - name: iron-bank-secret
    envs:
      - secret/application.properties

generatorOptions:
  disableNameSuffixHash: false
  labels:
    type: generated
  annotations:
    note: generated

images:
 - name: iron-bank-server
   newName: ghcr.io/bnsouzas/iron-bank-v2
   newTag: _IMAGE_TAG

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
